spring.application.name=project-springboot-bd
spring.datasource.url=jdbc:mysql://localhost:3306/registration_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.ddl.hibernate.ddl-auto=update